# Generated by Django 3.0.7 on 2020-11-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bag', models.CharField(max_length=20)),
                ('description_bag', models.TextField(blank=True)),
                ('price_bag', models.PositiveIntegerField()),
                ('title_image', models.FileField(upload_to='bags/title/')),
                ('detail_big_image', models.FileField(upload_to='bags/detail_bags_images/')),
                ('detail_middle_image', models.FileField(upload_to='bags/detail_bags_images/')),
                ('bag_published_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('body', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bag_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_bag', to='bags.Bag')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
