# Generated by Django 3.0.7 on 2021-04-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0005_commentbag_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentbag',
            name='new_field',
            field=models.TextField(default=12, help_text='new field for test'),
            preserve_default=False,
        ),
    ]
