# Generated by Django 3.0.7 on 2020-12-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespondPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_responders', models.CharField(max_length=20)),
                ('text_of_responders', models.TextField()),
                ('name_of_office_worker', models.CharField(max_length=10)),
                ('avatat_image_of_responder', models.FileField(upload_to='responder_avatars/')),
            ],
        ),
    ]
