# Generated by Django 3.0.7 on 2020-12-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_childrenthingcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrenthingcomment',
            name='children_thing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='children.ChildrenThing'),
        ),
    ]
