# Generated by Django 3.0.7 on 2020-12-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_auto_20201222_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrenthingcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='children.ChildrenThingComment'),
        ),
    ]
