# Generated by Django 3.0.7 on 2020-08-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_blog_post', models.CharField(max_length=20)),
                ('description_blog_post', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('image_blog_post', models.FileField(upload_to='blog/')),
            ],
        ),
    ]
