# Generated by Django 3.0.7 on 2020-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200809_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentblogpost',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentblogpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentblogpost',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
