# Generated by Django 3.0.7 on 2020-08-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200809_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentblogpost',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='commentblogpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.CommentBlogPost'),
        ),
        migrations.AlterField(
            model_name='commentblogpost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
