# Generated by Django 3.0.7 on 2020-12-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
