# Generated by Django 3.0.7 on 2021-01-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
